### ISSUE TITLE
Title not shown in Special:SpecialPages

### ISSUE THREAD

**Issue by lakejason0** [AlPha5130/mediawiki-extensions-EditCountNeue#5]
![image](https://user-images.githubusercontent.com/36039861/190838929-63ef2ef1-e944-451a-ad85-7542674417b7.png)

**Comment by AlPha5130** [comment]
Fixed in commit [9bef48a](https://github.com/AlPha5130/mediawiki-extensions-EditCountNeue/commit/9bef48ad3799d550f8aa7b713a873eb350b061ab).
